# The Site Configuration

theme: jekyll-theme-chirpy

lang: en
timezone: Asia/Ho_Chi_Minh

title: Blog of Minh Cuong
tagline: Cybersecurity • Pentesting • Writeups
description: >-
  Personal blog of Minh Cuong focusing on cybersecurity, penetration testing,
  labs, and technical writeups.

# ⚠️ BẮT BUỘC cho GitHub Pages user site
url: "https://mrminhcuong.github.io"
baseurl: ""

github:
  username: mrminhcuong

social:
  name: Nguyen Minh Cuong
  email: minhcuong.sec@gmail.com
  links:
    - https://github.com/mrminhcuong

toc: true
paginate: 10

theme_mode:
cdn:
avatar: /assets/img/avatar.png

comments:
  provider:

pwa:
  enabled: true
  cache:
    enabled: true

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true
      comments: false
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

exclude:
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
